[project]
name = "gex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.2.0",
    "jax[cuda12]",
    "numpy>=2",
    "tyro>=0.9",
]
